"""Gaokao NL2SQL：自然语言转只读 SQL。"""

from __future__ import annotations

from gaokao_nl2sql.catalog import (
    AdmissionConfidence,
    AvailabilityGate,
    AvailabilityInfo,
    CatalogPipeline,
    CatalogResult,
    CandidateProfile,
    Citation,
    CitationBuilder,
    ClassifiedQuery,
    ConfidenceBand,
    ConfidenceReference,
    ConversionResult,
    CoverageWarning,
    DataScope,
    DataCoverageRegistry,
    DataScopeRegistry,
    EntityResolver,
    GateDecision,
    IntentExtractor,
    OpenAICompatibleSqlAnswerSynthesizer,
    QueryCategory,
    QueryFilters,
    QueryOutput,
    QueryPlan,
    QueryPlanner,
    QueryClassifier,
    QueryScope,
    ResultAnnotation,
    ResultAnnotator,
    ScopeResolver,
    ScoreRankConverter,
    ScoreSegment,
    SemanticFrame,
    SemanticFrameExtractor,
    SqlAnswerSynthesizer,
    SqlCompiler,
    UnavailableReason,
)
from gaokao_nl2sql.errors import (
    Nl2SqlError,
    SqlExecutionError,
    SqlGenerationError,
    UnsafeSqlError,
)
from gaokao_nl2sql.executor import PostgresExecutor, QueryExecutor
from gaokao_nl2sql.generator import SqlGenerator, extract_sql
from gaokao_nl2sql.guard import validate_select_sql
from gaokao_nl2sql.llm import ChatModel, OpenAICompatibleModel
from gaokao_nl2sql.pipeline import Nl2SqlPipeline, Nl2SqlResult
from gaokao_nl2sql.schema_context import (
    ALLOWED_TABLES,
    SCHEMA_CONTEXT,
    build_schema_context,
)

__all__ = [
    "AdmissionConfidence",
    "ALLOWED_TABLES",
    "AvailabilityGate",
    "AvailabilityInfo",
    "CatalogPipeline",
    "CatalogResult",
    "CandidateProfile",
    "Citation",
    "CitationBuilder",
    "SCHEMA_CONTEXT",
    "ChatModel",
    "ClassifiedQuery",
    "ConfidenceBand",
    "ConfidenceReference",
    "ConversionResult",
    "CoverageWarning",
    "DataScope",
    "DataCoverageRegistry",
    "DataScopeRegistry",
    "EntityResolver",
    "GateDecision",
    "IntentExtractor",
    "Nl2SqlError",
    "Nl2SqlPipeline",
    "Nl2SqlResult",
    "OpenAICompatibleSqlAnswerSynthesizer",
    "OpenAICompatibleModel",
    "PostgresExecutor",
    "QueryCategory",
    "QueryFilters",
    "QueryOutput",
    "QueryPlan",
    "QueryPlanner",
    "QueryClassifier",
    "QueryExecutor",
    "QueryScope",
    "ResultAnnotation",
    "ResultAnnotator",
    "ScopeResolver",
    "ScoreRankConverter",
    "ScoreSegment",
    "SemanticFrame",
    "SemanticFrameExtractor",
    "SqlAnswerSynthesizer",
    "SqlCompiler",
    "SqlExecutionError",
    "SqlGenerationError",
    "SqlGenerator",
    "UnsafeSqlError",
    "UnavailableReason",
    "build_schema_context",
    "extract_sql",
    "validate_select_sql",
]
